import Header from "@/components/shared/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import Footer from "@/components/shared/Footer";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={` ${nunito.className} bg-gray-50 text-gray-950`}>
                <div className="backdround bg-blue-200 -z-10 absolute top-[-20%] left-[10%] w-[32rem] h-[32rem] rounded-full blur-[250px]"></div>
                <div className="backdround bg-red-200 -z-10 absolute top-[-20%] right-[10%] w-[32rem] h-[32rem] rounded-full blur-[250px]"></div>
                <Header />
                <main className="page-content">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
